sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: lyx050127

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tRxxsKFtWMBDxyvy3ci
    access-key-secret: SscUwpNQNxrE1hLVE12hBKPpXSDn3w
    bucket-name: sky-take-out-colin

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0

  wechat:
    appid: wx80300fad313b44a1
    secret: 177b5f101a3e0496b6e6f9c24cbc0394